default:
  image: node:18.17.0

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  POSTGRES_DB: invoicesync
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  REGISTRY_USER: $REGISTRY_USER
  IMAGE_NAME: $IMAGE_NAME
  IMAGE_TAG: latest
  CONTAINER_NAME: $CONTAINER_NAME
  GCP_USERNAME: $GCP_USERNAME
  GCP_STATIC_IP: $GCP_STATIC_IP

stages:
  - build
  - test
  - publish
  - deploy

Build:
 stage: build
 image: gradle:jdk17-alpine
 before_script:
   - echo `pwd`
   - ls
   - cd invoicesync
   - export GRADLE_USER_HOME=`pwd`/.gradle
 script:
   - ls
   - gradle wrapper
   - ./gradlew assemble
   - ls
 artifacts:
   when: always
   paths:
     - invoicesync/build/libs/*.jar
   expire_in: 1 week

Publish:
 stage: publish
 image: docker:20.10.16
 dependencies:
   - Build
 before_script:
   - sudo apt install docker.io
   - docker login -u $REGISTRY_USER -p $DOCKER_HUB_TOKEN
 script:
   - ls
   - docker build --build-arg PRODUCTION=$PRODUCTION --build-arg JDBC_DATABASE_URL=$JDBC_DATABASE_URL -t $REGISTRY_USER/$IMAGE_NAME:$IMAGE_TAG .
   - docker push $REGISTRY_USER/$IMAGE_NAME:$IMAGE_TAG
 only:
   - main

Deploy:
 stage: deploy
 image: alpine:latest
 before_script:
   - chmod 400 $SSH_KEY
   - apk update && apk add openssh-client
 script:
   - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $AWS_USERNAME@$AWS_IP "
     docker container rm -f $CONTAINER_NAME || true &&
     docker image rm -f $REGISTRY_USER/$IMAGE_NAME:$IMAGE_TAG || true &&
     docker run --name $CONTAINER_NAME -d -p 80:8080 $REGISTRY_USER/$IMAGE_NAME:$IMAGE_TAG"
 only:
   - main

# Deployment Vercel
deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - cd invoicesync-frontend
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - cd invoicesync-frontend
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN